### ISSUE TITLE
How to close the connection via ebpf code

### ISSUE THREAD

**Issue by arayu05** [l3af-project/eBPF-Package-Repository#23]
On connection limiting:
 i want to close the connection once it exceeds a limit instead of dropping. I tried this by sending FIN packet from server side to initiate connection close.
If i set FIN flag on the packet and do XDP_TX if does as below:

![Screenshot from 2022-05-30 21-51-56](https://user-images.githubusercontent.com/83341997/172899668-640823d7-8d00-418e-9825-938986621f9f.png)

See the info part in screenshot, Here 172.17.0.4 is Client and 172.17.0.1 is LB.
When at first the Syn packet came from  4 -> 1 , the server got it and replied to LB with Ack and then LB routes that to the client with fin flag set(so see the Syn, Ack and Fin flag set in next line).

Then further the client send the Ack back for which server send RST flag. So this happens many times both ways.
Connection does close but not gracefully it seems.

What is a good way to close few connections on reaching certain limit?

**Comment by jniesz** [comment]
I would recommend sending a "RST, ACK" instead of the "FIN, ACK" or just drop new connections (XDP_DROP). If you are trying to drop existing connections I would recommend FIN, but you would have to identify the specific connections you want to drop. 

I am going to close this as it is not related to our connection limiting program.
